name: media_scanner
description: A Flutter plugin to refresh the system gallery after saving images/videos.
  Supports Android and OpenHarmony.
version: 1.0.0
homepage: https://pub.dev/packages/media_scanner
repository: https://github.com/LazyCatLabs/media_scanner

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      ohos:
        default_package: media_scanner_ohos

dependencies:
  flutter:
    sdk: flutter
  media_scanner_ohos:
    path: ../media_scanner_ohos

dev_dependencies:
  flutter_test:
    sdk: flutter
