/**
 * This source code is licensed under the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree.
 */

import { RNPackageContext, RNPackage } from '@rnoh/react-native-openharmony/ts';
// GEN:RN_PACKAGE_IMPORTS_BEGIN
// GEN:RN_PACKAGE_IMPORTS_END

export function createRNPackages(ctx: RNPackageContext): RNPackage[] {
  return [
    // GEN:RN_PACKAGE_LIST_BEGIN
    // GEN:RN_PACKAGE_LIST_END
  ];
}
