#!/usr/bin/env python3
"""Validate ModuleTest.test.ets completeness after sub-integration-test writes it.

Fixed paths (relative to plugin repo CWD):
  App.tsx           → ohos/example/App.tsx
  AppScope          → ohos/example/harmony/AppScope/app.json5  (bundleName)
  entry module      → ohos/example/harmony/entry/src/main/module.json5  (EntryAbility)
  ModuleTest        → ohos/example/harmony/entry/src/ohosTest/ets/test/ui/ModuleTest.test.ets

Usage:
    python validate_module_test.py --methods getBarColor,setBarMode
    python validate_module_test.py --file ... --methods ...   # override paths if needed

Exit: 0 ok; 1 validation failed; 2 usage error
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

TAG = "[validate-module-test]"

# TurboModule 内部方法：须在 ETS 实现，但 onDeviceTest 不要求单独 it() / App 按钮
# （常量由公开 API 或静态字段间接验证，见 primary-04-testing.md §4.0）
DEVICE_TEST_EXCLUDED_METHODS = frozenset({"getConstants"})


def filter_device_test_methods(methods: list[str]) -> list[str]:
    """Remove methods that must not have standalone Hypium it() blocks."""
    return [m for m in methods if m not in DEVICE_TEST_EXCLUDED_METHODS]


# RN-OHOS convention: example test page always at this path
DEFAULT_APP_TSX = Path("ohos/example/App.tsx")
DEFAULT_APP_JSON5 = Path("ohos/example/harmony/AppScope/app.json5")
DEFAULT_ENTRY_MODULE = Path("ohos/example/harmony/entry/src/main/module.json5")
DEFAULT_MODULE_TEST = Path(
    "ohos/example/harmony/entry/src/ohosTest/ets/test/ui/ModuleTest.test.ets"
)


def read_json5_quoted_field(path: Path, field: str) -> str | None:
    if not path.is_file():
        return None
    text = path.read_text(encoding="utf-8", errors="replace")
    m = re.search(rf'"{re.escape(field)}"\s*:\s*"([^"]+)"', text)
    return m.group(1) if m else None


def read_entry_ability_name(entry_module_path: Path) -> str | None:
    if not entry_module_path.is_file():
        return None
    text = entry_module_path.read_text(encoding="utf-8", errors="replace")
    m = re.search(r'"mainElement"\s*:\s*"([^"]+)"', text)
    if m:
        return m.group(1)
    m = re.search(
        r'"abilities"\s*:\s*\[\s*\{\s*"name"\s*:\s*"([^"]+)"',
        text,
    )
    return m.group(1) if m else None


def parse_module_test_launch_constants(test_text: str) -> tuple[str | None, str | None]:
    bundle_m = re.search(
        r"const\s+BUNDLE_NAME\s*=\s*['\"]([^'\"]+)['\"]",
        test_text,
    )
    ability_m = re.search(
        r"const\s+ENTRY_ABILITY\s*=\s*['\"]([^'\"]+)['\"]",
        test_text,
    )
    return (
        bundle_m.group(1) if bundle_m else None,
        ability_m.group(1) if ability_m else None,
    )


def parse_app_testids(app_path: Path) -> set[str]:
    text = app_path.read_text(encoding="utf-8", errors="replace")
    # Extract literal testID="xxx" or testID='xxx'
    ids = set(re.findall(r'testID\s*=\s*["\']([^"\']+)["\']', text))
    
    # Extract testID from object property assignments (testID: 'xxx',)
    # This handles dynamic testID passing: testID={testCase.testID}
    for m in re.finditer(r"testID\s*:\s*['\"]([^'\"]+)['\"]", text):
        ids.add(m.group(1))
    
    # Extract testID from renderTestButton(...) calls (third parameter)
    # Pattern: renderTestButton('methodName', ..., 'test-xxx-btn')
    for m in re.finditer(r"renderTestButton\s*\(\s*[^,]+,\s*[^,]+,\s*['\"]([^'\"]+)['\"]\s*\)", text):
        test_id = m.group(1)
        ids.add(test_id)
    
    # Extract dynamic testID from renderResult('methodName') calls
    # Pattern: testID={`result-${method}`} is generated by renderResult('methodName')
    for m in re.finditer(r"renderResult\s*\(\s*['\"]([\w-]+)['\"]\s*\)", text):
        method_name = m.group(1)
        ids.add(f"result-{method_name}")
    
    return ids


def parse_method_button_ids(test_text: str) -> dict[str, str]:
    """Parse METHOD_BUTTON_IDS: Record<string, string> = { 'slug': 'btn-xxx', ... }"""
    start = test_text.find("METHOD_BUTTON_IDS")
    if start < 0:
        return {}
    chunk = test_text[start : start + 4000]
    return {
        m.group(1): m.group(2)
        for m in re.finditer(
            r"['\"]([\w-]+)['\"]\s*:\s*['\"]([^'\"]+)['\"]",
            chunk,
        )
        if m.group(2).startswith(("btn-", "test-"))
    }


def collect_waitfor_literals(test_text: str) -> set[str]:
    ids: set[str] = set()
    for m in re.finditer(r"waitForId\([^,]+,\s*[`']([^`']+)[`']", test_text):
        val = m.group(1)
        if "${" not in val:
            ids.add(val)
    return ids


def load_example_test_ids(example_path: Path) -> set[str]:
    if not example_path.is_file():
        return set()
    try:
        data = json.loads(example_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return set()
    out: set[str] = set()
    coverage = data.get("method_coverage") or {}
    if not isinstance(coverage, dict):
        return out
    for entry in coverage.values():
        if not isinstance(entry, dict):
            continue
        tid = entry.get("test_id")
        if not isinstance(tid, str) or not tid.strip():
            continue
        for part in tid.split(","):
            part = part.strip()
            if part and part not in ("implicit", "hook-bluetooth-state"):
                out.add(part)
    return out


def validate_testid_alignment(test_text: str, app_path: Path) -> list[str]:
    """ModuleTest testIDs must exist in fixed ohos/example/App.tsx."""
    errors: list[str] = []
    if not app_path.is_file():
        errors.append(
            f"App.tsx not found (expected fixed path): {app_path}. "
            "Run example generation first."
        )
        return errors

    app_ids = parse_app_testids(app_path)
    if not app_ids:
        errors.append(f"No testID= found in {app_path}")
        return errors

    button_map = parse_method_button_ids(test_text)
    for slug, tid in button_map.items():
        if tid not in app_ids:
            errors.append(
                f"METHOD_BUTTON_IDS['{slug}'] uses '{tid}' but App.tsx has no testID={tid}"
            )

    literals = collect_waitfor_literals(test_text)
    for tid in literals:
        if tid not in app_ids and tid not in button_map.values():
            errors.append(f"waitForId references '{tid}' not present in App.tsx testID")

    uses_legacy = "test-${method}-btn" in test_text and "METHOD_BUTTON_IDS" not in test_text
    app_has_btn = any(i.startswith("btn-") for i in app_ids)
    if uses_legacy and app_has_btn:
        errors.append(
            "ModuleTest uses legacy test-${method}-btn template but App.tsx uses btn-* testIDs; "
            "add METHOD_BUTTON_IDS from ohos/example/App.tsx"
        )

    return errors


def validate_bundle_ability_alignment(
    test_text: str,
    app_json5_path: Path,
    entry_module_path: Path,
) -> list[str]:
    """BUNDLE_NAME / ENTRY_ABILITY in ModuleTest must match fixed Example config files."""
    errors: list[str] = []

    expected_bundle = read_json5_quoted_field(app_json5_path, "bundleName")
    if expected_bundle is None:
        errors.append(
            f"bundleName not found in {app_json5_path} (fixed AppScope path). "
            "Run example build / ohos-sync-build-profile first."
        )
    expected_ability = read_entry_ability_name(entry_module_path)
    if expected_ability is None:
        errors.append(
            f"Entry ability not found in {entry_module_path} (expected mainElement or abilities[0].name)."
        )

    actual_bundle, actual_ability = parse_module_test_launch_constants(test_text)
    if actual_bundle is None:
        errors.append("ModuleTest missing const BUNDLE_NAME = '...' (do not hardcode in startEntryAbility only)")
    if actual_ability is None:
        errors.append("ModuleTest missing const ENTRY_ABILITY = '...'")

    if expected_bundle and actual_bundle and actual_bundle != expected_bundle:
        errors.append(
            f"BUNDLE_NAME mismatch: ModuleTest has '{actual_bundle}', "
            f"{app_json5_path} has bundleName '{expected_bundle}'"
        )
    if expected_ability and actual_ability and actual_ability != expected_ability:
        errors.append(
            f"ENTRY_ABILITY mismatch: ModuleTest has '{actual_ability}', "
            f"entry module expects '{expected_ability}'"
        )

    if "startEntryAbility" in test_text:
        for line in test_text.splitlines():
            stripped = line.strip()
            if re.search(r"bundleName:\s*['\"]", stripped) and "BUNDLE_NAME" not in stripped:
                errors.append(
                    "startEntryAbility must use bundleName: BUNDLE_NAME, not a literal bundleName string"
                )
                break
            if re.search(r"abilityName:\s*['\"]", stripped) and "ENTRY_ABILITY" not in stripped:
                errors.append(
                    "startEntryAbility must use abilityName: ENTRY_ABILITY, not a literal abilityName string"
                )
                break
        if "bundleName: BUNDLE_NAME" not in test_text:
            errors.append("startEntryAbility must reference bundleName: BUNDLE_NAME")
        if "abilityName: ENTRY_ABILITY" not in test_text:
            errors.append("startEntryAbility must reference abilityName: ENTRY_ABILITY")

    return errors


def example_json_warnings(app_path: Path, example_path: Path) -> list[str]:
    """Optional: 04-testing test_id drift vs App.tsx (does not block)."""
    warnings: list[str] = []
    if not example_path.is_file() or not app_path.is_file():
        return warnings
    app_ids = parse_app_testids(app_path)
    for tid in load_example_test_ids(example_path):
        if (tid.startswith("btn-") or tid.startswith("test-")) and tid not in app_ids:
            warnings.append(
                f"04-testing test_id '{tid}' not in App.tsx (update 04-testing or App.tsx)"
            )
    return warnings


def validate(
    path: Path,
    methods: list[str],
    app_path: Path,
    app_json5_path: Path,
    entry_module_path: Path,
    example_path: Path | None = None,
) -> dict:
    errors: list[str] = []
    warnings: list[str] = []
    if not path.is_file():
        return {"ok": False, "errors": [f"file not found: {path}"], "warnings": warnings}

    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    stripped = text.rstrip()

    if not stripped.endswith("}"):
        errors.append("file does not end with closing brace (likely truncated mid-write)")

    if "export default function moduleTest" not in text:
        errors.append("missing export default function moduleTest()")

    open_braces = text.count("{")
    close_braces = text.count("}")
    if open_braces != close_braces:
        errors.append(f"unbalanced braces: {{={open_braces} }}={close_braces}")

    it_blocks = re.findall(r"\bit\s*\(\s*['\"]([^'\"]+?)['\"]", text)
    testable_methods = filter_device_test_methods(methods)
    required_its = {"detectWhiteScreen"} | set(testable_methods)
    missing_its = sorted(required_its - set(it_blocks))
    if missing_its:
        errors.append(f"missing it() blocks: {', '.join(missing_its)}")

    for helper in ("waitForText", "waitForId", "findMethodButton", "beforeAll"):
        if helper not in text:
            errors.append(f"missing helper or hook: {helper}")

    errors.extend(validate_testid_alignment(text, app_path))
    errors.extend(validate_bundle_ability_alignment(text, app_json5_path, entry_module_path))
    if example_path:
        warnings.extend(example_json_warnings(app_path, example_path))

    return {
        "ok": len(errors) == 0,
        "errors": errors,
        "warnings": warnings,
        "details": {
            "path": str(path),
            "app_path": str(app_path),
            "app_json5_path": str(app_json5_path),
            "entry_module_path": str(entry_module_path),
            "line_count": len(lines),
            "it_count": len(it_blocks),
            "it_names": it_blocks,
            "methods_expected": sorted(required_its),
            "methods_excluded": sorted(set(methods) - set(testable_methods)),
            "methods_input": methods,
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate ModuleTest.test.ets")
    parser.add_argument(
        "--file",
        default=str(DEFAULT_MODULE_TEST),
        help=f"Path to ModuleTest.test.ets (default: {DEFAULT_MODULE_TEST})",
    )
    parser.add_argument(
        "--methods",
        default="",
        help="Comma-separated implemented method names (excl. detectWhiteScreen)",
    )
    parser.add_argument(
        "--app",
        default=str(DEFAULT_APP_TSX),
        help=f"Override App.tsx path (default fixed: {DEFAULT_APP_TSX})",
    )
    parser.add_argument(
        "--example-json",
        default="",
        help="Optional: warn if 04-testing test_id drifts from App.tsx (non-blocking)",
    )
    parser.add_argument(
        "--cwd",
        default=".",
        help="Plugin repo root (default: current directory)",
    )
    args = parser.parse_args()

    cwd = Path(args.cwd).resolve()
    methods_raw = [m.strip() for m in args.methods.split(",") if m.strip()]
    methods = filter_device_test_methods(methods_raw)
    excluded = sorted(set(methods_raw) - set(methods))
    if excluded:
        print(
            f"{TAG} Info: excluded from device-test it() requirement: {', '.join(excluded)}",
            file=sys.stderr,
        )
    test_path = cwd / args.file
    app_path = cwd / args.app
    app_json5_path = cwd / DEFAULT_APP_JSON5
    entry_module_path = cwd / DEFAULT_ENTRY_MODULE
    example_path = (cwd / args.example_json) if args.example_json else None

    result = validate(
        test_path, methods, app_path, app_json5_path, entry_module_path, example_path
    )

    for w in result.get("warnings", []):
        print(f"{TAG} WARN: {w}", file=sys.stderr)

    if result["ok"]:
        d = result["details"]
        print(
            f"{TAG} Pass: {d['line_count']} lines, {d['it_count']} it() blocks, "
            f"app={d['app_path']}, bundle={d.get('app_json5_path')}"
        )
        sys.exit(0)

    print(f"{TAG} Failed:", file=sys.stderr)
    for e in result["errors"]:
        print(f"{TAG}   {e}", file=sys.stderr)
    sys.exit(1)


def _configure_stdio_utf8() -> None:
    """Windows 终端/管道下按 UTF-8 输出中文与符号，避免 UnicodeEncodeError 崩溃。"""
    if not sys.platform.startswith("win"):
        return
    try:
        import ctypes
        ctypes.windll.kernel32.SetConsoleOutputCP(65001)
        ctypes.windll.kernel32.SetConsoleCP(65001)
    except Exception:
        pass
    for _name in ("stdout", "stderr"):
        _stream = getattr(sys, _name, None)
        if _stream is None or not hasattr(_stream, "reconfigure"):
            continue
        try:
            _stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, OSError, ValueError):
            pass


_configure_stdio_utf8()


if __name__ == "__main__":
    main()
