import React, { useState } from 'react';
import { ScrollView, View, Text, TouchableOpacity, StyleSheet } from 'react-native';

// TODO: import plugin
// import { PluginModule } from 'original-package-name';

interface TestResult {
  status: 'idle' | 'running' | 'success' | 'fail';
  message: string;
  details?: string;
}

interface TestCase {
  id: string;
  title: string;
  level: string;
  moduleCode: string;
  moduleName: string;
}

interface Module {
  code: string;
  name: string;
  testCases: TestCase[];
}

const modules: Module[] = [
  // Generated by generate_example.py
];

export default function App() {
  const [currentModule, setCurrentModule] = useState<string | null>(null);
  const [currentTestCase, setCurrentTestCase] = useState<string | null>(null);
  const [result, setResult] = useState<TestResult>({ status: 'idle', message: '' });

  const renderModuleIndex = () => (
    <View style={styles.container}>
      <Text style={styles.header}>测试模块列表</Text>
      <ScrollView>
        {modules.map(module => (
          <TouchableOpacity
            key={module.code}
            testID={`module_${module.code}`}
            style={styles.moduleCard}
            onPress={() => setCurrentModule(module.code)}
          >
            <Text style={styles.moduleName}>{module.name}</Text>
            <Text style={styles.moduleInfo}>测试用例: {module.testCases.length}</Text>
          </TouchableOpacity>
        ))}
      </ScrollView>
    </View>
  );

  const renderModulePage = () => {
    const module = modules.find(m => m.code === currentModule);
    if (!module) return null;

    return (
      <View style={styles.container}>
        <TouchableOpacity
          testID="btn_back"
          style={styles.backButton}
          onPress={() => setCurrentModule(null)}
        >
          <Text style={styles.backText}>← 返回模块列表</Text>
        </TouchableOpacity>
        <Text style={styles.header}>{module.name}</Text>
        <ScrollView>
          {module.testCases.map(tc => (
            <TouchableOpacity
              key={tc.id}
              testID={`testcase_${tc.id}`}
              style={styles.testCaseCard}
              onPress={() => setCurrentTestCase(tc.id)}
            >
              <Text style={styles.testCaseTitle}>{tc.title}</Text>
              <Text style={styles.testCaseLevel}>级别: {tc.level}</Text>
            </TouchableOpacity>
          ))}
        </ScrollView>
      </View>
    );
  };

  const renderTestCasePage = () => {
    const module = modules.find(m => m.code === currentModule);
    const testCase = module?.testCases.find(tc => tc.id === currentTestCase);
    if (!testCase) return null;

    return (
      <View style={styles.container}>
        <TouchableOpacity
          testID="btn_back_to_module"
          style={styles.backButton}
          onPress={() => setCurrentTestCase(null)}
        >
          <Text style={styles.backText}>← 返回用例列表</Text>
        </TouchableOpacity>
        <Text style={styles.header}>{testCase.title}</Text>
        <Text style={styles.subHeader}>级别: {testCase.level}</Text>
        
        <View style={styles.actionsContainer}>
          {/* TODO: Implement test actions based on test case */}
        </View>

        <ResultPanel result={result} />
      </View>
    );
  };

  if (currentTestCase) {
    return renderTestCasePage();
  }
  if (currentModule) {
    return renderModulePage();
  }
  return renderModuleIndex();
}

function ResultPanel({ result }: { result: TestResult }) {
  const statusColor = {
    idle: '#666',
    running: '#2196F3',
    success: '#4CAF50',
    fail: '#F44336',
  };

  return (
    <View style={styles.resultPanel}>
      <Text style={styles.resultLabel}>执行结果:</Text>
      <Text
        testID="txt_result"
        style={[styles.resultText, { color: statusColor[result.status] }]}
      >
        {result.message || '待执行'}
      </Text>
      {result.details && (
        <Text style={styles.resultDetails}>{result.details}</Text>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: '#f5f5f5',
  },
  header: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
    color: '#333',
  },
  subHeader: {
    fontSize: 14,
    marginBottom: 8,
    color: '#666',
  },
  moduleCard: {
    padding: 16,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  moduleName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  moduleInfo: {
    fontSize: 12,
    color: '#666',
    marginTop: 4,
  },
  testCaseCard: {
    padding: 12,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 8,
  },
  testCaseTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
  },
  testCaseLevel: {
    fontSize: 12,
    color: '#666',
    marginTop: 4,
  },
  backButton: {
    marginBottom: 16,
  },
  backText: {
    fontSize: 14,
    color: '#2196F3',
  },
  actionsContainer: {
    marginTop: 16,
    gap: 8,
  },
  resultPanel: {
    marginTop: 24,
    padding: 16,
    backgroundColor: '#fff',
    borderRadius: 8,
  },
  resultLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  resultText: {
    fontSize: 16,
    fontWeight: '500',
  },
  resultDetails: {
    fontSize: 12,
    color: '#666',
    marginTop: 4,
  },
});