#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Test cases-driven HAR Demo skeleton generator for Android SDK.
# Parse 04-test-cases.json to get modules and test cases, then generate:
#   - entry/src/main/ets/pages/Index.ets (module list)
#   - entry/src/main/ets/pages/ModuleF##_Page.ets (test case list for module)
#   - entry/src/main/ets/pages/TestCaseF##_##Page.ets (test case detail page)
#   - entry/src/main/ets/widgets/ResultPanel.ets
#   - entry/src/main/resources/base/profile/main_pages.json (page routes)
#
# The generator ONLY produces skeleton structure with TODO markers.
# Filling in Actions/Result logic is done by the LLM in a subsequent step.
#

import argparse
import json
import os
import re
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Dict, Any

sys.path.insert(0, str(Path(__file__).parent))
from _common import (
    DEFAULT_GENERATE_LEVELS,
    case_id_to_class_name,
    case_id_to_file_name,
    case_id_to_route,
    escape_ets_string,
    format_test_steps,
    infer_library_module_name,
    load_json5,
    parse_covered_apis,
    parse_levels,
    read_json,
    should_generate,
)

# Resolved from --levels at runtime; DEFAULT_GENERATE_LEVELS is the fallback.
GENERATE_LEVELS: List[str] = list(DEFAULT_GENERATE_LEVELS)


def main():
    args = parse_args()
    global GENERATE_LEVELS
    GENERATE_LEVELS = parse_levels(args.levels)
    
    # Step 1: Copy hardemo scaffold to ohos-hardemo-auto
    scaffold_dir = Path(args.scaffold)
    demo_output_dir = Path(args.out)
    
    if scaffold_dir.exists():
        if demo_output_dir.exists():
            print('INFO: Removing existing ohos-hardemo-auto directory...')
            try:
                shutil.rmtree(demo_output_dir)
            except PermissionError as e:
                print(f'WARN: Failed to remove directory due to file lock: {e}')
                print('INFO: Attempting to clean directory contents instead...')
                # Try to remove files individually
                for entity in demo_output_dir.rglob('*'):
                    if entity.is_file():
                        try:
                            entity.unlink()
                        except:
                            pass
        print('INFO: Copying hardemo scaffold to ohos-hardemo-auto...')
        copy_directory(scaffold_dir, demo_output_dir, critical=True)
        
        # Step 2: Clear ONLY pages/ and widgets/ (regenerated by this script).
        # Ability files and any other ets content are preserved as-is from the
        # scaffold — previously the script wiped the whole ets tree and restored
        # two hard-coded ability files, which dropped any extra abilities.
        entry_ets_dir = demo_output_dir / 'entry' / 'src' / 'main' / 'ets'
        for sub in ('pages', 'widgets'):
            sub_dir = entry_ets_dir / sub
            if sub_dir.exists():
                print(f'INFO: Clearing entry/src/main/ets/{sub}/ for regeneration...')
                shutil.rmtree(sub_dir, ignore_errors=True)
        
        # Step 2.5: Smart-copy library only when the scaffold did NOT already
        # bring a real HAR. In the fast flow `--scaffold ohos_hardemo` already
        # contains the real `library/`, so this step is skipped (the previous
        # implementation hard-coded `ohos-hardemo` and always printed a misleading
        # WARN). Candidates `ohos_hardemo` and `ohos-hardemo` are both tried.
        target_library_dir = demo_output_dir / 'library'
        scaffold_library_dir = scaffold_dir / 'library'
        scaffold_has_real_library = (
            scaffold_library_dir.exists()
            and (scaffold_library_dir / 'oh-package.json5').exists()
            and (scaffold_library_dir / 'src').exists()
        )
        if scaffold_has_real_library:
            print('INFO: Scaffold already contains a real library/, skipping smart-copy.')
        else:
            copied = False
            for candidate_name in ('ohos_hardemo', 'ohos-hardemo'):
                sdk_library_dir = Path.cwd() / candidate_name / 'library'
                if sdk_library_dir.exists() and (sdk_library_dir / 'oh-package.json5').exists():
                    print(f'INFO: Found {candidate_name}/library, copying complete HAR implementation...')
                    if target_library_dir.exists():
                        shutil.rmtree(target_library_dir, ignore_errors=True)
                    copy_directory(sdk_library_dir, target_library_dir, critical=True)
                    print(f'INFO: Copied complete HAR implementation from {sdk_library_dir}')
                    copied = True
                    break
            if not copied:
                print('WARN: No external library/ found; using scaffold library template (if any).')
        
        # Step 2.6: Infer library module name ONCE and inject dependency.
        library_module_name = infer_library_module_name(target_library_dir, log=True)
        entry_oh_package = demo_output_dir / 'entry' / 'oh-package.json5'
        if entry_oh_package.exists():
            print(f'INFO: Injecting library dependency ({library_module_name}) into entry/oh-package.json5...')
            inject_library_dependency(entry_oh_package, library_module_name)
        
        # Step 3: Delete non-essential directories
        non_essential_dirs = [
            demo_output_dir / 'entry' / 'build',
            demo_output_dir / 'entry' / '.hvigor',
            demo_output_dir / 'entry' / 'oh_modules',
            demo_output_dir / 'library' / 'build',
            demo_output_dir / 'library' / '.hvigor',
            demo_output_dir / 'library' / 'oh_modules',
            demo_output_dir / '.hvigor',
            demo_output_dir / 'oh_modules',
            demo_output_dir / 'node_modules',
        ]
        
        for dir_path in non_essential_dirs:
            if dir_path.exists():
                print(f'INFO: Removing non-essential directory: {dir_path}')
                shutil.rmtree(dir_path, ignore_errors=True)
    else:
        print(f'ERROR: Scaffold directory not found: {scaffold_dir.absolute()}')
        sys.exit(1)
    
    test_cases_file = Path(args.test_cases)
    if not test_cases_file.exists():
        print(f'ERROR: Test cases file not found: {test_cases_file.absolute()}')
        sys.exit(1)
    
    test_cases_data = read_json(test_cases_file)
    modules = parse_modules_from_test_cases(test_cases_data, GENERATE_LEVELS)
    
    if not modules:
        print('ERROR: No modules parsed. Check 04-test-cases.json structure.')
        sys.exit(1)
    
    if args.dry_run:
        print(f'DRY-RUN: would generate {len(modules)} module page(s)')
        print(f'INFO: 生成级别过滤: {", ".join(GENERATE_LEVELS)}')
        for m in modules:
            print(f'  - {m.id} -> pages/{m.file_name}')
            for tc in m.test_cases:
                print(f'    - {tc.case_id} [{tc.level}] -> pages/{tc.file_name}')
        print('  + Index.ets, ResultPanel.ets, main_pages.json')
        print('(no files written)')
        sys.exit(0)
    
    entry_ets_pages_dir = demo_output_dir / 'entry' / 'src' / 'main' / 'ets' / 'pages'
    entry_ets_widgets_dir = demo_output_dir / 'entry' / 'src' / 'main' / 'ets' / 'widgets'
    entry_resources_profile_dir = demo_output_dir / 'entry' / 'src' / 'main' / 'resources' / 'base' / 'profile'
    
    entry_ets_pages_dir.mkdir(parents=True, exist_ok=True)
    entry_ets_widgets_dir.mkdir(parents=True, exist_ok=True)
    entry_resources_profile_dir.mkdir(parents=True, exist_ok=True)
    
    sdk_name = args.sdk_name
    # library_module_name was already inferred once in Step 2.6; reuse it.
    
    # Get the directory where the script is located
    script_dir = Path(__file__).parent
    
    # Copy skeleton files
    copy_skeleton_file(
        source=script_dir / 'ets_skeleton' / 'widgets' / 'ResultPanel.ets',
        target=entry_ets_widgets_dir / 'ResultPanel.ets',
        replace={},
    )
    
    copy_skeleton_file(
        source=script_dir / 'ets_skeleton' / 'widgets' / 'TestInfoPanel.ets',
        target=entry_ets_widgets_dir / 'TestInfoPanel.ets',
        replace={},
    )
    
    # Generate Index.ets (module list page)
    write_module_index(entry_ets_pages_dir / 'Index.ets', modules, sdk_name)
    
    # Generate main_pages.json
    write_main_pages_json(entry_resources_profile_dir / 'main_pages.json', modules)
    
    # Generate module pages and test case pages
    for m in modules:
        write_module_page(
            path=entry_ets_pages_dir / m.file_name,
            module=m,
            sdk_name=sdk_name,
        )
        
        for tc in m.test_cases:
            write_test_case_page(
                path=entry_ets_pages_dir / tc.file_name,
                module=m,
                test_case=tc,
                sdk_name=sdk_name,
                library_module_name=library_module_name,
            )
    
    total_test_cases = sum(len(m.test_cases) for m in modules)
    print(f'OK: generated {len(modules)} module page(s) and {total_test_cases} test case page(s)')
    print(f'INFO: 生成级别过滤: {", ".join(GENERATE_LEVELS)}')
    print(f'INFO: Output directory: {demo_output_dir.absolute()}')
    print('Next: fill TODO markers in each Module*.ets and TestCase*.ets (see SKILL.md Step 2).')


# ---------------------------------------------------------------------------
# Args
# ---------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(
        description='Parse test-cases JSON and generate HAR Demo ETS skeleton with TODO markers.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
  python generate_hardemo_ets.py --sdk-name header-decor
  python generate_hardemo_ets.py --test-cases .ohos-adaptation/04-test-cases.json
  python generate_hardemo_ets.py --dry-run
        '''
    )
    parser.add_argument('--test-cases', default=None,
                        help='Path to test-cases JSON file (default: auto-detect 04-test-cases.json in .ohos-adaptation)')
    parser.add_argument('--scaffold', default=None,
                        help='Path to hardemo scaffold directory (default: ohos_hardemo)')
    parser.add_argument('--out', default=None,
                        help='Output demo root (default: ohos-hardemo-auto)')
    parser.add_argument('--sdk-name', default=None,
                        help='SDK name for display (default: extracted from 01-analysis.json)')
    parser.add_argument('--levels', default=','.join(DEFAULT_GENERATE_LEVELS),
                        help=f'Comma-separated case levels to generate, e.g. L0,L1 (default: {",".join(DEFAULT_GENERATE_LEVELS)}). '
                             f'Cases whose level is non-empty and not in this set are skipped (and logged).')
    parser.add_argument('--dry-run', action='store_true',
                        help='Print modules/paths; do not create or overwrite files')
    
    args = parser.parse_args()
    
    # Auto-detect 04-test-cases.json
    if args.test_cases is None:
        args.test_cases = find_test_cases_file()
    
    # Auto-detect scaffold directory
    if args.scaffold is None:
        args.scaffold = find_scaffold_directory()
    
    # Auto-detect output directory
    if args.out is None:
        args.out = 'ohos-hardemo-auto'
    
    # Auto-detect SDK name
    if args.sdk_name is None:
        args.sdk_name = read_sdk_name_from_analysis() or 'sdk-demo'
    
    return args


def find_test_cases_file() -> str:
    """Return path to test cases file (04-test-cases.json in .ohos-adaptation)."""
    original = Path('.ohos-adaptation/04-test-cases.json')
    return str(original)


def find_scaffold_directory() -> str:
    """Find scaffold directory; default to ohos_hardemo (fast flow)."""
    cwd = Path.cwd()
    # Fast flow: ohos_hardemo alongside .ohos-adaptation at SDK repo root.
    if (cwd / 'ohos_hardemo').exists():
        return 'ohos_hardemo'
    # Legacy fallback: agent-android-sdk/scaffold/hardemo in parents.
    for parent in cwd.parents:
        scaffold = parent / 'agent-android-sdk' / 'scaffold' / 'hardemo'
        if scaffold.exists():
            return str(scaffold)
    return 'ohos_hardemo'


def read_sdk_name_from_analysis() -> Optional[str]:
    """Read SDK name from 01-analysis.json (BOM-tolerant)."""
    f = Path('.ohos-adaptation/01-analysis.json')
    if not f.exists():
        return None
    try:
        data = read_json(f)
        return data.get('sdk_name', None)
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

@dataclass
class TestCase:
    case_id: str
    title: str
    level: str
    preconditions: str
    test_steps: List[str]  # pre-split step strings, emitted as a string[] to TestInfoPanel
    expected_result: str
    postconditions: str
    covered_apis_android: List[str] = field(default_factory=list)
    covered_apis_harmony: List[str] = field(default_factory=list)

    @property
    def class_name(self) -> str:
        return case_id_to_class_name(self.case_id)

    @property
    def file_name(self) -> str:
        return case_id_to_file_name(self.case_id)

    @property
    def page_route(self) -> str:
        return case_id_to_route(self.case_id)


@dataclass
class Module:
    id: str
    title: str
    description: str
    priority: str
    test_cases: List[TestCase] = field(default_factory=list)
    
    @property
    def class_name(self) -> str:
        return f'Module{self.id.replace("-", "")}Page'
    
    @property
    def file_name(self) -> str:
        return f'Module{self.id.replace("-", "")}Page.ets'
    
    @property
    def page_route(self) -> str:
        return f'pages/Module{self.id.replace("-", "")}Page'


def id_to_suffix(id_str: str) -> str:
    return id_str.replace('-', '')


# ---------------------------------------------------------------------------
# Test cases parsing
# ---------------------------------------------------------------------------

def parse_modules_from_test_cases(test_cases_data: Dict[str, Any], levels: List[str]) -> List[Module]:
    modules_data = test_cases_data.get('modules', [])
    modules: List[Module] = []
    skipped_count = 0
    
    for module_data in modules_data:
        if isinstance(module_data, dict):
            id_ = str(module_data.get('moduleCode', '') or '')
            title = str(module_data.get('moduleName', '') or '')
            description = str(module_data.get('moduleDescription', '') or '')
            priority = str(module_data.get('priority', '') or '')
            test_cases_data_list = module_data.get('test_cases') or module_data.get('testCases') or []
            
            if id_ and title:
                test_cases: List[TestCase] = []
                
                for test_case_data in test_cases_data_list:
                    if isinstance(test_case_data, dict):
                        case_id = str(test_case_data.get('id', '') or test_case_data.get('caseId', '') or '')
                        case_title = str(test_case_data.get('title', '') or '')
                        level = str(test_case_data.get('level', '') or '')
                        
                        # Apply the same level filter the checker uses (empty
                        # level is always kept). Skipped cases are counted and
                        # logged so nothing disappears silently.
                        if not should_generate(level, levels):
                            skipped_count += 1
                            continue
                        
                        if case_id and case_title:
                            preconditions = str(test_case_data.get('preconditions', '') or '')
                            expected_result = str(test_case_data.get('expected_result', '') or test_case_data.get('expected', '') or '')
                            postconditions = str(test_case_data.get('postconditions', '') or '')
                            
                            # Shared formatter returns a newline-joined string;
                            # split back into a list for string[] emission so the
                            # widget never has to parse a joined string.
                            steps_str = format_test_steps(test_case_data)
                            steps_list = [s for s in steps_str.split('\n') if s.strip()] or ['无']
                            
                            covered = parse_covered_apis(test_case_data)
                            
                            test_cases.append(TestCase(
                                case_id=case_id,
                                title=case_title,
                                level=level,
                                preconditions=preconditions,
                                test_steps=steps_list,
                                expected_result=expected_result,
                                postconditions=postconditions,
                                covered_apis_android=covered['android'],
                                covered_apis_harmony=covered['harmony'],
                            ))
                
                if test_cases:
                    modules.append(Module(
                        id=id_,
                        title=title,
                        description=description,
                        priority=priority,
                        test_cases=test_cases,
                    ))
    
    if skipped_count:
        print(f'INFO: Filtered out {skipped_count} test case(s) not in levels {levels}.')
    
    return modules


# ---------------------------------------------------------------------------
# oh-package.json5 helpers
# ---------------------------------------------------------------------------

def inject_library_dependency(oh_package_path: Path, library_module_name: str = 'library'):
    """Inject library dependency into entry/oh-package.json5 dependencies.
    
    Detection is structural (comment-stripped JSON5 parse via load_json5) so the
    actual module name is recognized regardless of naming (library /
    @scope/library / dotsindicator ...), avoiding duplicate injection that the
    old regex-only check could not prevent. Injection itself is a targeted
    string replacement to preserve comments and formatting.
    
    Args:
        oh_package_path: Path to entry/oh-package.json5
        library_module_name: Module name to use (e.g., 'library' or '@stickyheader/library')
    """
    content = oh_package_path.read_text(encoding='utf-8')
    
    # Structural detection: parse JSON5 (comments stripped, BOM-tolerant).
    try:
        pkg = load_json5(oh_package_path)
        deps = pkg.get('dependencies') or {}
        if isinstance(deps, dict) and library_module_name in deps:
            print('INFO: library dependency already exists in oh-package.json5, skipping')
            return
    except Exception as e:
        print(f'WARN: Failed to parse oh-package.json5 for detection: {e}; falling back to string injection')
    
    if '"dependencies"' not in content:
        print('WARN: No "dependencies" key found in entry/oh-package.json5')
        return
    
    # Empty dependencies block: "dependencies": {}
    pattern = r'"dependencies"\s*:\s*\{\s*\}'
    replacement = f'"dependencies": {{\n    "{library_module_name}": "file:../library"\n  }}'
    new_content, count = re.subn(pattern, replacement, content)
    if count > 0:
        oh_package_path.write_text(new_content, encoding='utf-8')
        print(f'INFO: Injected library dependency ({library_module_name}) into entry/oh-package.json5')
        return
    
    # Non-empty: insert right after the opening brace of dependencies.
    match2 = re.search(r'"dependencies"\s*:\s*\{', content)
    if match2:
        insert_pos = match2.end()
        new_content = content[:insert_pos] + f'\n    "{library_module_name}": "file:../library",' + content[insert_pos:]
        oh_package_path.write_text(new_content, encoding='utf-8')
        print(f'INFO: Injected library dependency ({library_module_name}) into existing dependencies')
    else:
        print('WARN: Could not locate dependencies block to inject')


# ---------------------------------------------------------------------------
# File writers
# ---------------------------------------------------------------------------

def copy_skeleton_file(source: Path, target: Path, replace: Dict[str, str]):
    if not source.exists():
        print(f'ERROR: skeleton missing: {source}')
        sys.exit(1)
    
    text = source.read_text(encoding='utf-8')
    for k, v in replace.items():
        text = text.replace(k, v)
    target.write_text(text, encoding='utf-8')


def write_main_pages_json(path: Path, modules: List[Module]):
    """Generate main_pages.json with all page routes."""
    pages = ['pages/Index']
    for m in modules:
        pages.append(m.page_route)
        for tc in m.test_cases:
            pages.append(tc.page_route)
    
    content = {
        "src": pages
    }
    
    path.write_text(json.dumps(content, indent=2), encoding='utf-8')


def write_module_index(path: Path, modules: List[Module], sdk_name: str):
    """Generate Index.ets - module list page (first level)."""
    
    module_entries = []
    for m in modules:
        subtitle = f'{m.description} · {m.priority} · {len(m.test_cases)}个测试用例'
        module_entries.append(f'''  {{
    moduleId: '{m.id}',
    title: '{m.id} {m.title}',
    subtitle: '{escape_ets_string(subtitle)}',
    pageRoute: '{m.page_route}'
  }}''')
    
    module_entries_text = ',\n'.join(module_entries)
    
    content = f'''import {{ router }} from '@kit.ArkUI';

interface ModuleEntry {{
  moduleId: string;
  title: string;
  subtitle: string;
  pageRoute: string;
}}

@Entry
@Component
struct Index {{
  private modules: ModuleEntry[] = [
{module_entries_text}
  ];

  build() {{
    Column() {{
      // 标题栏
      Row() {{
        Text('{sdk_name} Demo')
          .fontSize(20)
          .fontWeight(FontWeight.Bold)
          .margin({{ left: 16, right: 16, top: 12, bottom: 12 }})
      }}
      .width('100%')
      .backgroundColor('#F1F3F5')
      
      // 功能模块列表
      List() {{
        ForEach(this.modules, (item: ModuleEntry) => {{
          ListItem() {{
            Row() {{
              Column() {{
                Text(item.title)
                  .fontSize(16)
                  .fontWeight(FontWeight.Medium)
                  .margin({{ bottom: 4 }})
                Text(item.subtitle)
                  .fontSize(12)
                  .fontColor('#666666')
              }}
              .alignItems(HorizontalAlign.Start)
              .layoutWeight(1)
              
              Image($r('sys.media.ohos_ic_public_arrow_right'))
                .width(24)
                .height(24)
                .fillColor('#999999')
            }}
            .width('100%')
            .padding(16)
            .backgroundColor(Color.White)
            .borderRadius(8)
            .margin({{ top: 8, bottom: 8, left: 12, right: 12 }})
            .onClick(() => {{
              router.pushUrl({{ url: item.pageRoute }});
            }})
          }}
        }})
      }}
      .width('100%')
      .layoutWeight(1)
      .backgroundColor('#F1F3F5')
    }}
    .width('100%')
    .height('100%')
  }}
}}
'''
    
    path.write_text(content, encoding='utf-8')


def write_module_page(path: Path, module: Module, sdk_name: str):
    """Generate Module page - test case list page (second level)."""
    
    test_case_entries = []
    for tc in module.test_cases:
        test_case_entries.append(f'''  {{
    caseId: '{tc.case_id}',
    title: '{tc.case_id} {escape_ets_string(tc.title)}',
    level: '{tc.level}',
    pageRoute: '{tc.page_route}'
  }}''')
    
    test_case_entries_text = ',\n'.join(test_case_entries)
    
    content = f'''import {{ router }} from '@kit.ArkUI';

interface TestCaseEntry {{
  caseId: string;
  title: string;
  level: string;
  pageRoute: string;
}}

@Entry
@Component
struct {module.class_name} {{
  private testCases: TestCaseEntry[] = [
{test_case_entries_text}
  ];

  build() {{
    Column() {{
      // 标题栏
      Row() {{
        Image($r('sys.media.ohos_ic_public_arrow_left'))
          .width(24)
          .height(24)
          .fillColor('#333333')
          .onClick(() => {{
            router.back();
          }})
          .margin({{ left: 16 }})
        
        Text('{module.id} {escape_ets_string(module.title)}')
          .fontSize(18)
          .fontWeight(FontWeight.Bold)
          .margin({{ left: 12, right: 16, top: 12, bottom: 12 }})
          .layoutWeight(1)
      }}
      .width('100%')
      .backgroundColor('#F1F3F5')
      
      // 测试用例列表
      List() {{
        ForEach(this.testCases, (item: TestCaseEntry) => {{
          ListItem() {{
            Row() {{
              Column() {{
                Text(item.title)
                  .fontSize(15)
                  .fontWeight(FontWeight.Medium)
                  .margin({{ bottom: 4 }})
                Text('优先级: ' + item.level)
                  .fontSize(12)
                  .fontColor('#666666')
              }}
              .alignItems(HorizontalAlign.Start)
              .layoutWeight(1)
              
              Image($r('sys.media.ohos_ic_public_arrow_right'))
                .width(24)
                .height(24)
                .fillColor('#999999')
            }}
            .width('100%')
            .padding(16)
            .backgroundColor(Color.White)
            .borderRadius(8)
            .margin({{ top: 8, bottom: 8, left: 12, right: 12 }})
            .onClick(() => {{
              router.pushUrl({{ url: item.pageRoute }});
            }})
          }}
        }})
      }}
      .width('100%')
      .layoutWeight(1)
      .backgroundColor('#F1F3F5')
    }}
    .width('100%')
    .height('100%')
  }}
}}
'''
    
    path.write_text(content, encoding='utf-8')


def write_test_case_page(path: Path, module: Module, test_case: TestCase, sdk_name: str, library_module_name: str = 'library'):
    """Generate Test Case page - detail page (third level).
    
    Args:
        path: Output file path
        module: Module data
        test_case: Test case data
        sdk_name: SDK name for display
        library_module_name: Library module name for import (e.g., 'library' or '@stickyheader/library')
    """
    # test_steps is emitted as a string[] literal (TestInfoPanel now takes an
    # array), so the widget never parses a joined string.
    steps_items = test_case.test_steps
    if steps_items:
        inner = ',\n'.join(f"            '{escape_ets_string(s)}'" for s in steps_items)
        test_steps_literal = f'[\n{inner}\n          ]'
    else:
        test_steps_literal = '[]'

    # coveredApis.android is surfaced as a wiring hint (see primary-sdk-demo-gen
    # Step 3 "功能点模型对齐"); coveredApis.harmony is backfilled by the LLM.
    android_apis_str = ', '.join(test_case.covered_apis_android) if test_case.covered_apis_android else '(none)'
    harmony_apis_str = ', '.join(test_case.covered_apis_harmony) if test_case.covered_apis_harmony else '[]'

    content = f'''import {{ router }} from '@kit.ArkUI';
import {{ ResultPanel }} from '../widgets/ResultPanel';
import {{ TestInfoPanel }} from '../widgets/TestInfoPanel';
// TODO(import-{test_case.case_id}): 从 '{library_module_name}' 导入本用例需要的组件/类型。
//   示例: import {{ SomeComponent, SomeType }} from '{library_module_name}';
//   coveredApis.android: [{android_apis_str}] → 在 library/Index.ets 定位对应 HAR API 接线
//   coveredApis.harmony: {harmony_apis_str} → 实现后回填到 .ohos-adaptation/04-test-cases.json
//   规则与完整示例见 references/code-patterns.md（示例一~十二）与 common-errors.md。

@Entry
@Component
struct {test_case.class_name} {{
  @State result: string = '等待操作 {test_case.case_id}...';

  build() {{
    Column() {{
      // 标题栏（固定）
      Row() {{
        Image($r('sys.media.ohos_ic_public_arrow_left'))
          .width(24)
          .height(24)
          .fillColor('#333333')
          .onClick(() => {{
            router.back();
          }})
          .margin({{ left: 16 }})

        Text('{test_case.case_id} {escape_ets_string(test_case.title)}')
          .fontSize(18)
          .fontWeight(FontWeight.Bold)
          .margin({{ left: 12, right: 16, top: 12, bottom: 12 }})
          .layoutWeight(1)
      }}
      .width('100%')
      .backgroundColor('#F1F3F5')

      // 可滚动区域（测试信息 + Actions）
      Scroll() {{
        Column() {{
          // ╔─ FIXED SECTION: 测试信息区（使用 TestInfoPanel 组件）─ 禁止修改 ─╗
          TestInfoPanel({{
            level: '{escape_ets_string(test_case.level)}',
            preconditions: '{escape_ets_string(test_case.preconditions)}',
            test_steps: {test_steps_literal},
            expected_result: '{escape_ets_string(test_case.expected_result)}',
            postconditions: '{escape_ets_string(test_case.postconditions)}'
          }})
          // ╚─ FIXED SECTION END ─╝

          // Actions 区
          Column() {{
            Text('Actions')
              .fontSize(16)
              .fontWeight(FontWeight.Bold)
              .margin({{ bottom: 8 }})

            // TODO(actions-{test_case.case_id}): 按 test_steps 第 3 步起的动作语义映射控件：
            //   纯触发型 → Button(动词+对象)；输入型 → Text+TextInput(@State)+Button；选择型 → Text+Select+Button。
            //   渲染验证类（checkpoint/expected_result 含"显示/渲染/动画/布局/滚动"等）须挂视觉预览组件，
            //     禁止只把数据 dump 到 result 冒充渲染（组合渲染正例见 code-patterns.md 示例十二）。
            //   异步回调/Resource 包装类：必须从 resource.data 取真实数据（见 code-patterns.md 图片加载示例）。
            //   每个控件加 .id()；onClick 职责单一；回调中更新 this.result（见下方 TODO(result)）。
            // @status: TODO  ← 实现后删除此标记与下方占位，替换为真实控件（check_implementation_status 以此判定）
            Column() {{
              Text('待实现 {test_case.case_id}：请根据测试用例类型填充内容')
                .fontSize(12)
                .fontColor('#999999')
                .textAlign(TextAlign.Center)
                .width('100%')
                .padding(16)
            }}
            .width('100%')
            .height(100)
            .justifyContent(FlexAlign.Center)
          }}
          .padding({{ left: 12, right: 12, top: 12, bottom: 12 }})
          .width('100%')
        }}
      }}
      .width('100%')
      .layoutWeight(1)
      .backgroundColor('#F1F3F5')
      .scrollBar(BarState.Auto)
      .scrollBarWidth(4)
      .scrollBarColor('#CCCCCC')

      // TODO(result-{test_case.case_id}): 操作触发后用 HAR 真实返回值/状态替换占位 '等待操作 {test_case.case_id}...'：
      //   API 类 → `成功: ${{res}}` / 'error: ' + e.message；展示型 → `状态名: ${{值}}`；禁止写死虚假文案。详见 result-format.md。
      ResultPanel({{ result: this.result }})
        .height(120)
    }}
    .width('100%')
    .height('100%')
  }}
}}
'''

    path.write_text(content, encoding='utf-8')


def copy_directory(source: Path, destination: Path, critical: bool = False):
    """Copy a directory recursively.

    Args:
        critical: when True, a missing critical file (oh-package.json5 /
            build-profile.json5 / Index.ets) aborts with sys.exit(1) instead of
            being silently skipped — a dropped scaffold file otherwise surfaces
            only as a later compile failure.
    """
    destination.mkdir(parents=True, exist_ok=True)
    critical_names = {'oh-package.json5', 'build-profile.json5', 'Index.ets'}
    skipped = 0
    missing_critical: List[Path] = []
    for entity in source.iterdir():
        try:
            if entity.is_dir():
                copy_directory(entity, destination / entity.name, critical=critical)
            elif entity.is_file():
                shutil.copy2(entity, destination / entity.name)
        except Exception as e:
            skipped += 1
            print(f'WARN: Skipping entity during copy: {entity}, error: {e}')
            if critical and entity.name in critical_names:
                missing_critical.append(entity)
    if skipped:
        print(f'WARN: Skipped {skipped} entity/entities while copying {source}')
    if missing_critical:
        print('ERROR: Critical files missing after copy:')
        for f in missing_critical:
            print(f'  - {f}')
        sys.exit(1)


if __name__ == '__main__':
    main()